#pragma once
enum TimeStatus { INCOUNTING, OVERTIME, CLOSED, NOTOVER };
enum WrongGesture { HEAD_FOREWARD, HEAD_RIGHT, HEAD_LEFT, ASIDE_BODY_FOREWARD, ASIDE_HEAD_FOREWARD, WRONGGESTURE_SIZE };
enum PlayMode { PLAYMODE_DEPTH = 1, PLAYMODE_COLOR, PLAYMODE_DEPTH_AND_COLOR };
enum AnlyzeMode { ANLYZEMODE_FRONT, ANLYZEMODE_ASIDE, ANLYZEMODE_SIZE };
enum JointData{ TEMP, LEFT_SHOULDER, RIGHT_SHOULDER, NECK, LEFT_HIP, RIGHT_HIP, LEFT_ELBOW, RIGHT_ELBOW, TORSO, HEAD, SHOULDER_ASIDE, HEAD_ASIDE, JOINTDATA_SIZE };
enum InfoIndex{ INFO_SHOULDER_DISTANCE, INFO_MAX_DISTANCE, INFO_HEAD_FB, INFO_HEAD_LR, INFO_TORSO, INFO_HEAD_ASIDE, INFO_ERROR_CODE, INFO_POSITION, INFO_SIZE };